# Generated by Django 5.0.7 on 2024-08-03 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0009_alter_book_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
    ]
